### ISSUE TITLE
[SUGGESTION] EnderZoo and Primitive Mobs support

### ISSUE THREAD

**Issue by Sunconure11** [Konlii/OrganicCreepers#1]
Both add their own variants on creepers

**Comment by Konlii** [comment]
Hmm, I haven't played either of those mods, so I am not sure.  I do know that I would have to create new types of Creeper Plants specific to those creeper variants.

**Comment by Konlii** [comment]
Creeper checks now look directly for Vanilla creeper class, so modded creepers should be untouched.

I doubt I will add any more support than this and just let other mods control their own custom creeper spawning mechanics.
