### ISSUE TITLE
Crashes when ghast fireballs or TNT minecarts explode

### ISSUE THREAD

**Issue by EpicQuackIV** [Konlii/OrganicCreepers#3]
[(ghast_fireball)crash-2019-04-09_21.37.02-server.txt](https://github.com/Konlii/OrganicCreepers/files/3061626/ghast_fireball.crash-2019-04-09_21.37.02-server.txt)

[(tnt_minecarts)crash-2019-04-09_21.22.51-server.txt](https://github.com/Konlii/OrganicCreepers/files/3061627/tnt_minecarts.crash-2019-04-09_21.22.51-server.txt)

**Comment by Konlii** [comment]
I see the problem. As soon as I can get to my computer I should have a fix for you.

**Comment by Konlii** [comment]
Fixed in 1.2.3
