### ISSUE TITLE
[Issue] Spores only spread south-east

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [Konlii/OrganicCreepers#6]
When creepers or creeper plants explode, their spores only travel in south-east direction (positive x and z values). If I were to guess, I would say that the algorithm for randomizing spore trajectory doesn't include negative values.

**Comment by Konlii** [comment]
Spores are definitely 100% random and are working perfectly from exploding plants.  I think possibly creepers were occasionally blocking some of the spores from their own explosion which made it _look_ like they were only firing in one direction.

v1.2.5 should make sure that doesn't happen.
